name: Build and deploy ASP.Net Core app to Azure Web App - instagramapihub

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2  # Updated to v2 for the latest version

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v7  # Updated to v7 for the latest version
        with:
          dotnet-version: '7.x'
          include-prerelease: true

      - name: Build with dotnet
        run: dotnet build Instagram.sln --configuration Debug

      - name: Publish with dotnet
        run: dotnet publish -c Debug -o ${{env.DOTNET_ROOT}}/myapp

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v2  # Updated to v2 for the latest version
        with:
          name: .net-app
          path: ${{env.DOTNET_ROOT}}/myapp

  deploy:
    runs-on: windows-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v2  # Updated to v2 for the latest version
        with:
          name: .net-app

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'instagramapihub'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_C1565AF0D3044A03905AF055E46899B7 }}
          package: .net-app
